ADD Proprietary Macro Changes from lok repo [MACRO-2201]
chase/lok-wasm pull request #18
Opened 2024-04-16 21:37 UTC by synoet

since `git am -3` is horrible at resolving any kind of conflict / rejection, I had to manually copy paste all the changes over from each commit diff during each patch apply. So its possible some things are missing / got improperly ported over, though I'll do my best to catch anything during testing.

Also some of the commits arent true to their original content since things had to be slightly moved around, but the overall change set is mostly the same.

this excludes commits for:
- v8 related stuff
- .as api
- backups
- colorizer / overlays
- windows / mac specific stuff

**:warning: IMPORTANT: DONT SQUASH THIS PR**

2024-04-17 22:41 UTC, gbirman commented
Squashing time

2024-04-17 22:43 UTC, synoet commented
I can prob rebase and drop my self as the co-author from all these commits, though realistically each one has some small changes

2024-04-18 05:17 UTC, chase commented
> I can prob rebase and drop my self as the co-author from all these commits, though realistically each one has some small changes

Don't bother.

Also, we can drop the code for lokdocumenteventnotifier and related, the document event hooks caused problems @synoet

This still needs to be reviewed, unnecessary code needs to be eliminated.

I'm going to mark this as draft until this is thoroughly tested and cleaned up.

2024-04-18 10:09 UTC, chase requested changes
See my comments below.

Also please go back and add the `MACRO:` comments I mentioned in a comment below to all of our proprietary code.

2024-04-18 10:09 UTC, chase commented on VERSIOn
Remove

2024-04-18 10:09 UTC, chase commented on libreoffice-core/Repository.mk
> +	custom_macro_fonts \
Remove, not necessary

2024-04-18 10:09 UTC, chase commented on libreoffice-core/comphelper/Library_comphelper.mk
> +    comphelper/source/misc/inthash \
Remove, not necessary

2024-04-18 10:09 UTC, chase commented on libreoffice-core/desktop/Library_sofficeapp.mk
> +    desktop/source/lib/lokdocumenteventnotifier \
Remove, not necessary

2024-04-18 10:09 UTC, chase commented on libreoffice-core/desktop/inc/lib/init.hxx
> +        std::unique_ptr<doceventnotifier::LokDocumentEventNotifier> m_lokDocEventNotifier;
Revert the commit that introduced this, not necessary

2024-04-18 10:09 UTC, chase commented on libreoffice-core/desktop/inc/lib/init.hxx
> +#include "../source/lib/lokdocumenteventnotifier.hxx"
Revert the commit that introduced this, not necessary

2024-04-18 10:09 UTC, chase commented on libreoffice-core/desktop/source/lib/init.cxx
> +        // If the document is loaded readonly, we need to set it to false.
Long ranges (not a couple lines) of Macro changes should be paired with an opening and closing like:
```
// MACRO: We are doing weird stuff {
...
...
...
...
// MACRO: }
```

This makes it easier to cut out or identify our changes to upstream during merge conflicts _and_ if need be, remove it if/when we requested to open source things.

2024-04-18 10:09 UTC, chase commented on libreoffice-core/desktop/source/lib/init.cxx
> +void setPageColor(LibreOfficeKitDocument* pThis, const OUString rColorHex)
See comment above about `// MACRO: ... {` comments.

Any proprietary change should be wrapped in it, excluding `#include` statements at the top.

2024-04-18 10:09 UTC, chase commented on libreoffice-core/desktop/source/lib/init.cxx
> +static void doc_setAuthor(LibreOfficeKitDocument* pThis, const char* sAuthor);
For single line proprietary changes, a single `/// MACRO: ` line is sufficient. If there is no ticket ID explicitly tied to it or it's hard to find the ticket ID, it can be omitted.

2024-04-18 10:09 UTC, chase commented on libreoffice-core/desktop/source/lib/init.cxx
> +
This seems extraneous. mxOwner is unused.

2024-04-18 10:09 UTC, chase commented on libreoffice-core/desktop/source/lib/init.cxx
> +}
New ticket and PR (@synoet please write it up for me and start on it as a medium priority after this is done):
We should rework any code that uses this, move them to wasm_extensions.hxx/wasm_extensions.cxx to return `std::string` and let embind handle the string lifetime appropriately.

Leaking memory isn't something we can afford since memory is limited to 2GB and each page that's allocated is 64KiB.

2024-04-18 10:09 UTC, chase commented on libreoffice-core/desktop/source/lib/lokdocumenteventnotifier.cxx
PR for this should be reverted, this code removed

2024-04-18 10:09 UTC, chase commented on libreoffice-core/desktop/source/lib/lokdocumenteventnotifier.hxx
PR for this should be reverted, this code removed

2024-04-18 10:09 UTC, chase commented on libreoffice-core/extras/Module_extras.mk
> +	Package_custom_macro_fonts \
PR for this should be reverted, this code removed

2024-04-18 10:09 UTC, chase commented on libreoffice-core/extras/Package_custom_macro_fonts.mk
PR for this should be reverted, this code removed

2024-04-18 10:09 UTC, chase commented on libreoffice-core/extras/source/macro_fonts/Caladea-Bold.ttf
PR for this should be reverted, macro_fonts should be removed

2024-04-18 10:09 UTC, chase commented on libreoffice-core/include/LibreOfficeKit/LibreOfficeKitEnums.h
PR for these changes should be reverted, these changes removed

2024-04-18 10:09 UTC, chase commented on libreoffice-core/include/LibreOfficeKit/LibreOfficeKitInit.h
This change isn't accurate anymore, should be reverted

2024-04-18 10:09 UTC, chase commented on libreoffice-core/include/rtl/string.hxx
These changes can be reverted, we compile with C++ exception support since WASM supports them natively now.

Any code added with a new condition of `#if defined SAL_NO_EXCEPT` can safely be reverted.

2024-04-18 10:09 UTC, chase commented on libreoffice-core/include/rtl/ustring.hxx
See above comment. Can be reverted.

2024-04-18 10:09 UTC, chase commented on libreoffice-core/officecfg/registry/data/org/openoffice/Office/Common.xcu
PR for these changes should be reverted, these changes removed

2024-04-18 10:09 UTC, chase commented on libreoffice-core/officecfg/registry/schema/org/openoffice/Office/Writer.xcs
> +>>>>>>> No bold in LOK changed attribute
Unresolved merge conflict. Choose HEAD.
```suggestion
            <value>0</value><!-- MACRO: Disable bold on LOK changed attribute (since we disabled coloring) -->
```

2024-04-18 10:09 UTC, chase commented on libreoffice-core/sfx2/source/doc/objstor.cxx
> +    // HERE
Extraneous change, should be removed

2024-04-18 10:09 UTC, chase commented on libreoffice-core/sw/inc/viewopt.hxx
> +    bool IsIndexShadings() const {return false;}
Since support was added upstream for toggling these, this change should be reverted instead of hard-coded.

2024-04-18 10:09 UTC, chase commented on libreoffice-core/sw/source/core/text/macro_internal.cxx
This is colorizer code. This PR/these changes should be reverted.

2024-04-18 10:09 UTC, chase commented on libreoffice-core/sw/source/core/text/atrstck.cxx
This is colorizer code. This PR/these changes should be reverted.

2024-04-18 10:09 UTC, chase commented on libreoffice-core/sw/source/core/text/macro_internal.hxx
This is colorizer code. This PR/these changes should be reverted.

2024-04-18 10:09 UTC, chase commented on libreoffice-core/sw/source/filter/ww8/docxexport.hxx
Should probably revert this extraneous change (not the commit, just the changes to this file). It makes it easier to handle merge conflicts later.

2024-04-18 10:09 UTC, chase commented on patches/0.patch
Looks like you accidentally added a temporary `patches` directory to this PR.

2024-04-18 11:12 UTC, synoet commented on patches/0.patch
yeah sorry, I included them temporarily just to keep track of them, when I had to make changes which patches I explicitly dropped. I'll remove them ofcourse before merging

2024-04-18 12:31 UTC, synoet commented on patches/0.patch
removed

2024-04-18 13:16 UTC, synoet commented on libreoffice-core/comphelper/Library_comphelper.mk
> +    comphelper/source/misc/inthash \
@chase Are you sure its used in `libreoffice-core/sw/source/filter/ww8/wrtww8.hxx`, for `MACRO-1786`

2024-04-18 13:55 UTC, chase commented
Oops, forgot to delete that comment. You're right, it's used for the export
optimization on Flutter.

On Thu, Apr 18, 2024, 20:16 teo ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In libreoffice-core/comphelper/Library_comphelper.mk
> <https://github.com/coparse-inc/lok-wasm/pull/18#discussion_r1570728532>:
>
> > @@ -168,6 +168,7 @@ $(eval $(call gb_Library_add_exception_objects,comphelper,\
>      comphelper/source/xml/attributelist \
>      comphelper/source/xml/ofopxmlhelper \
>      comphelper/source/xml/xmltools \
> +    comphelper/source/misc/inthash \
>
> @chase <https://github.com/chase> Are you sure its used in
> libreoffice-core/sw/source/filter/ww8/wrtww8.hxx, for MACRO-1786
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/coparse-inc/lok-wasm/pull/18#discussion_r1570728532>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAABKI52O5Z67BIWFGEPHYDY57BTPAVCNFSM6AAAAABGKEBZ6KVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDAMBYHA3TCNRVGI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-04-18 14:32 UTC, synoet commented on libreoffice-core/desktop/source/lib/init.cxx
> +}
https://www.notion.so/macrocom/Move-things-that-use-leakyStrDup-to-wasm-extensions-eebd0795686347e28f653587ca6b2ddf

2024-04-18 15:06 UTC, synoet commented
@chase Update: 
- removed all unneeded changes and dropped their commits
- Added // MACRO: comments to all of our changes 
- Added back loadDocumentFromMemory , saveToMemory
- things are compiling / working as expected

Only thing i noticed is blue additions are not underlines.

2024-04-18 16:21 UTC, synoet commented
@chase fixed underlines + merged in main

2024-04-19 11:23 UTC, chase approved these changes

2024-04-19 11:24 UTC, merged