Multi View Rendering + Document Preview [MACRO-2212]
chase/lok-wasm pull request #34
Opened 2024-05-15 19:02 UTC by synoet

#### Description
- [x] Refactor `tile_renderer_worker` to support rendering multiple views at once.
- [x] Adds an `AdditionalView` struct which can be created and appended to `TileRenderData`.
  - This allows views to be added and removed dynamically even after the `tileRendererWorker` has started.
  - Each `AdditionalView` supports being rendered at a different `tileSize` if needed.
- [x] Invalidations are debounced for the preview view and prioritized for the main view. So that invalidations are only painted once the main view has gone idle.
- [x] Painting / Rendering for the preview view will be paused if the main view stops idling.
- [x] Handling for missing tiles during rendering. Adds them to a list, and then commits them as invalidations on the next idle.
- [x] General changes to how painting/rendering is handled for scrolling and zooming.
- [x] Adds new `previewStart` and `previewStop` methods to tile renderer that allow dynamically starting and stopping rendering of only the preview view.
- [x] `pendingFullPaint` is per view, so zooming in on the mainView does not cause a RESET of the previewView.  
- [x] Adds some visual debugging helpers, including a tile border along with a timestamped id and tile row, column positions.
  - timestamped id is `(timeTilePainted - timeWorkerStarted)` , so lower numbers indicate an earlier paint.

This logic should be easy to extend if we decide in the future that we want to add another view *(example: Picture in Picture Window)*

#### Outstanding
*:warning: There are still some outstanding issues, mostly existed before this pr. I will address these issues separately*
- [ ] Invalidation issued by undo is not correct. Causes performance issues. (Existed Before)
- [x] Cannot type on initial cursor position, have to move it. (Existed Before)
- [ ] Extremely quick zoom + scroll wheel can end up rendering on the wrong canvas (Existed Before)

*Toggling Preview, Scrolling, Invalidations Video:*

https://github.com/coparse-inc/lok-wasm/assets/10552019/7e77ce54-7cf5-4ec0-9b39-33a1b8a84010

*Tile Debugging Screenshot:*

![image](https://github.com/coparse-inc/lok-wasm/assets/10552019/85d53d93-9c34-4124-842b-9496221ea2b3)

2024-05-22 11:33 UTC, chase requested changes
Good work overall, please resolve the mentioned issues and resolve the merge conflicts.

Diff is a little messy because of all the reorganizing that was done.

I understand you had to split things off into a class for the tile renderer code, but otherwise try not to move things around unless strictly necessary since it makes reviewing harder.

2024-05-22 11:33 UTC, chase commented on libreoffice-core/desktop/inc/lib/wasm_extensions.hxx
> +    uint8_t* paintedTile;
Is there a reason this was rearranged and `tileTwips` was changed to an `std::array`?

2024-05-22 11:33 UTC, chase commented on libreoffice-core/desktop/inc/lib/wasm_extensions.hxx
> -                     uint32_t docWidthTwips_, uint32_t docHeightTwips_)
Is there a reason this was changed?

2024-05-22 11:33 UTC, chase commented on libreoffice-core/desktop/source/app/main_wasm.cxx
> +                   emscripten::typed_memory_view(1, (int32_t*)&data.invalidationStackHead));
Drop `emscripten::` prefix. This isn't necessary since `using namespace emscripten;` is used at the top.

2024-05-22 11:33 UTC, chase commented on libreoffice-core/desktop/source/app/main_wasm.cxx
> +        emscripten::val result = emscripten::val::object();
Drop `emscripten::` here, not necessary.

2024-05-22 11:33 UTC, chase commented on libreoffice-core/desktop/source/app/main_wasm.cxx
> +    register_optional<int32_t>();
I don't think this is used, is it?

2024-05-22 11:33 UTC, chase commented on libreoffice-core/desktop/source/lib/wasm_extensions.cxx
> +#include <optional>
Unused.

2024-05-22 11:33 UTC, chase commented on libreoffice-core/desktop/source/lib/wasm_extensions.cxx
> +    /* __builtin_wasm_memory_atomic_notify((int32_t*)&hasInvalidations, MAX_THREADS_TO_NOTIFY); */
Why was this disabled? This prevents the atomic from changing in the frontend.

2024-05-22 11:33 UTC, chase commented on libreoffice-core/desktop/wasm/index.ts
> +    }
Be more specific about the fix here.
Why are you replacing the `newView` here method when that's already in `clientBase`?

2024-05-22 11:33 UTC, chase commented on libreoffice-core/desktop/wasm/shared.d.ts
> +    yPos: number | undefined
Is this no longer in pixels?

2024-05-22 11:33 UTC, chase commented on libreoffice-core/desktop/wasm/shared.d.ts
> +    // scale: number
?

2024-05-22 11:33 UTC, chase commented on libreoffice-core/desktop/wasm/shared.d.ts
> +    dpi: number,
Why are we passing DPI here? Tile size is reliant on DPI.

2024-05-22 11:33 UTC, chase commented on libreoffice-core/desktop/wasm/soffice.d.ts
> +  /** `_Atomic uint32_t` */
This is not correct

2024-05-22 11:33 UTC, chase commented on libreoffice-core/desktop/wasm/tile_renderer_worker.ts
> +import { TileRenderData } from './soffice';
?

2024-05-22 11:33 UTC, chase commented on libreoffice-core/desktop/wasm/tile_renderer_worker.ts
> +const DEBUG = true;
```suggestion
const DEBUG = false;
```

2024-05-22 11:33 UTC, chase commented on qa-env/src/OfficeDocument/OfficeDocument.tsx
> +    if (height && didInitialRender.has(props.doc)) props.doc.setVisibleHeight(height);
What's this for? Doesn't this prevent the canvas height from being passed until a second render event occurs?

2024-05-22 11:33 UTC, chase commented on qa-env/src/OfficeDocument/OfficeDocument.tsx
> +    console.log("startRendering")
```suggestion
```

2024-05-22 11:33 UTC, chase commented on libreoffice-core/desktop/wasm/tile_renderer_worker.ts
> +  validTiles: Set<number> = new Set();
```suggestion
  /** contains a set of all the valid tile indices */
  validTiles: Set<number> = new Set();
```

2024-05-22 11:33 UTC, chase commented on libreoffice-core/desktop/wasm/tile_renderer_worker.ts
> +function debouncedPostActiveCanvas(index: number) {
Gut check is this is maybe not right. Because if the active canvas is out of sync, double buffering won't work correctly. The events themselves should probably be debounced, not the results, I think? Unless I'm misunderstanding where this is called.

2024-05-22 11:35 UTC, chase commented
Also could you expand on what you meant by this, @teo? 

>  Invalidation issues by undo is not correct. Causes performance issues. (Existed Before)

Is this one issue? The invalidations are not correct _and_ the behavior causes perf issues as a result?

2024-05-22 15:11 UTC, synoet commented on libreoffice-core/desktop/inc/lib/wasm_extensions.hxx
> +    uint8_t* paintedTile;
Ah yeah, sorry this was an artifact of when i had the previewTileTwips on the TileRenderData as an `std::optional` which wouldn't take an arbitrary type. Will undo back

2024-05-22 15:14 UTC, synoet commented on libreoffice-core/desktop/source/app/main_wasm.cxx
> +    register_optional<int32_t>();
yup, sorry again artifact from when the preview view data was an optional.

2024-05-22 15:26 UTC, synoet commented on libreoffice-core/desktop/wasm/index.ts
> +    }
I think the recent changes broke the proper handling for `newView`, it seems to just forward the call to the worker and then forward the response back without actually invoking the `newView` method on the `clientBase`. I'll properly fix it instead, this was just temporary.

2024-05-22 15:29 UTC, synoet commented on libreoffice-core/desktop/wasm/shared.d.ts
> +    dpi: number,
DPI was being passed before aswell, if you look at `worker.ts`. The type was just incorrect.

2024-05-22 15:42 UTC, synoet commented
> Also could you expand on what you meant by this, @teo?
> 
> > Invalidation issues by undo is not correct. Causes performance issues. (Existed Before)
> 
> Is this one issue? The invalidations are not correct _and_ the behavior causes perf issues as a result?

Sorry this was a typo I meant to say `Invalidation issued`, meaning I think the invalidation event when an undo event happens is not always correct, and doesn't cause the right area to always be repainted. @chase

2024-05-22 15:52 UTC, synoet commented on libreoffice-core/desktop/wasm/tile_renderer_worker.ts
> +function debouncedPostActiveCanvas(index: number) {
you're right, removed.

2024-05-23 10:54 UTC, chase approved these changes

2024-05-23 10:54 UTC, merged