Expanded Storage [MACRO-2283]
chase/lok-wasm pull request #43
Opened 2024-05-23 16:41 UTC by synoet

# Expanded Storage

### Description
Adds support for loading and saving docx files to their individual parts in memory.  
Instead of relying on ZIP storage, files within the docx are stored in memory and retrieved as needed.  

### API
`d.loadFromExpandedParts()`: loads a document from a list of parts (`{ path: string , content: ArrayBuffer }`)  
`d.listExpandedParts()`: will return a list of doc parts in the form `{ path: string, sha: string }`  
`d.getExpandedPart(path)`: will return a single part given the path `{ path: string, content: ArrayBuffer }`  

### Requirements 
- [x] Load document from expanded parts  
- [x] Save document to its own expanded storage (inplace save)  
- [x] Loading of normal DOCX files works as it does before  
- [x] Save As -> PDF  
- [x] Save As -> DOCX (this will be done by exporting the current storage & re-zipping if needed)  

### Implementation Notes
ExpandedStorage implements two important classes `StorageBase` and `XStorage`.

`XStorage` is the underlying abstraction for storage, and it is responsible for a variety of tasks most importantly fetching input and output streams given a path.

Other implementations of `XStorage` are hierarchical. there is one storage for each "directory" within the zip file. for example to access elements within the `word` directory of the docx file, one would traditionally call `openSubStorage` which would initialize its contents and relationships.

Expanded storage works slightly differently. It is initialized with all the content up front. Things like relationships which are stored in `.rels` files at different levels are also initialized at the top level of the storage.

Hierarchical access is faked. the actual files in the storage live behind a shared pointer to a unordered map of path -> `Expanded File { path , content, sha}`. When calling `openSubStorage(path)` on the expanded storage it initializes a new instance of the storage with a seperate `basePath`, however the underlying files are simply shared between instances. 

`comphelper::OStorageHelper` contains three globals: 

`bIsExpandedStorage`: which gets set during the `loadFromExpanded` method.
`expandedStorage`: this is the `XStorage` instance.
`expandeStorageBase`: this is the `StorageBase` instance.

In traditional fs based storage lok primarily passed around a stream, which it will then convert to a storage on the fly. However, this is not viable with expanded storage since there is no single input stream. Instead we need to rely on methods that allow us to fetch the corresponding storage where anywhere in the import/export flows.

### Existing Issues
- [x] Images don't seem to be properly loaded

2024-06-26 13:21 UTC, synoet commented
@chase I think this should be ready for a first pass on your end. There are definitely still a couple of loose ends that need to be cleaned up:
- the api for loading a document from expanded storage is just what I came up with during testing, should discuss with @gbirman & @whutchinson98 to flesh it out a bit more
- There are several places where I've added a return or just commented a block of code out. There are code paths that I noticed we might not need during the load file execution. 
- I haven't properly added MACRO comments to all proprietary code yet, but will once the pr has been reviewed / made changes to it.

2024-06-27 08:11 UTC, chase commented
> Images don't seem to be properly loaded

Any leads on why?

2024-06-27 12:44 UTC, synoet commented on libreoffice-core/sw/source/core/unocore/unotext.cxx
> +        /* m_pDoc->GetIDocumentUndoRedo().Undo(); */
sorry this was left over from testing

2024-06-27 13:34 UTC, chase requested changes

2024-06-27 13:34 UTC, chase commented on libreoffice-core/comphelper/source/misc/storagehelper.cxx
> +#include "com/sun/star/embed/XStorage.hdl"
You probably want `.hxx` instead of `.hdl` here, because this can lead to the class not being instantiated.
Clangd doesn't handle this well and I'm assuming this was auto added.

Also, reminder that for includes they should be `<...hxx`> instead of `"...hxx" unless they are relative to the file. This is the standard in upstream because relative includes slow down compile time because they have to be resolved and repeatedly instead of just once.

2024-06-27 13:34 UTC, chase commented on libreoffice-core/comphelper/source/streaming/vecstream.cxx
> +    std::copy(data.getConstArray(), data.getConstArray() + data.getLength(), m_vec.data() + m_pos);
Better to use memcpy since it compiles to a single fast intrinsic for WASM whereas it's up to the C++ optimizer whether std::copy does the right thing (don't trust it in this case :joy:):

https://github.com/emscripten-core/emscripten/blob/a864ddec6ac3384e2f125728ef05efd6eddff04d/system/lib/libc/emscripten_memcpy.c#L22-L28

2024-06-27 13:34 UTC, chase commented on libreoffice-core/desktop/source/lib/init.cxx
> +static void* lo_getXComponentContext(LibreOfficeKit* pThis);
You actually don't need this since there's already: `comphelper::getProcessComponentContext()` from `#include <comphelper/processfactory.hxx>`, saves having to shuffle it around

2024-06-27 13:34 UTC, chase commented on libreoffice-core/desktop/source/lib/init.cxx
> +            comphelper::makePropertyValue(u"FilterName"_ustr, OUString("MS Word 2007 XML")),
Is this necessary? Just curious.

2024-06-27 13:34 UTC, chase commented on libreoffice-core/desktop/source/lib/wasm_extensions.cxx
> +    uno::Reference<frame::XDesktop2> xComponentLoader = frame::Desktop::create(xContext);
```suggestion
    uno::Reference<frame::XDesktop2> xComponentLoader = frame::Desktop::create(comphelper::getProcessComponentContext());
```

2024-06-27 13:34 UTC, chase commented on libreoffice-core/desktop/source/lib/wasm_extensions.cxx
> +    uno::Reference<io::XInputStream> xEmptyInputStream(new comphelper::SequenceInputStream(aEmptyData));
Is there a reason why VectorInputStream isn't used here as well? Also not really empty later, so maybe needs a better name.

2024-06-27 13:34 UTC, chase commented on libreoffice-core/desktop/source/lib/wasm_extensions.cxx
> +        storage->addPart(it->path, it->content);
```suggestion
        storage->addPart(it->path, std::move(it->content));
```

Since the original parts are erased, instead of copying, move the string.

2024-06-27 13:34 UTC, chase commented on libreoffice-core/desktop/source/lib/wasm_extensions.cxx
> +    parts.emplace_back(path, content);
```suggestion
    parts.emplace_back(path, std::move(content));
```

Instead of copying, move the string since the original content is removed or only on stack at some point anyway.

2024-06-27 13:34 UTC, chase commented on libreoffice-core/desktop/wasm/shared.d.ts
> +  loadFromExpandedParts(data: Array<{path: string, content: string}>): DocumentRef | null;
content should be `ArrayBuffer`

2024-06-27 13:34 UTC, chase commented on libreoffice-core/desktop/wasm/shared.d.ts
> +  getExpandedPart(path: string): {path: string, content: string} | null;
content should be `ArrayBuffer`

2024-06-27 13:34 UTC, chase commented on libreoffice-core/desktop/wasm/index.ts
> -  viewId: number | undefined = -1
Is there a reason why? -1 indicates an invalid view while 0 is actually the default view ID for LOK.

2024-06-27 13:34 UTC, chase commented on libreoffice-core/desktop/wasm/index.ts
> +  parts: Array<{path: string, content: string}>
content should be an ArrayBuffer that is a transferable, that way we don't copy the part data unnecessarily after loading

2024-06-27 13:34 UTC, chase commented on libreoffice-core/desktop/wasm/worker.ts
> +    const doc = new Document(expandedDoc, "test");
Probably want to preserve the original file name somehow instead of just `"test"` for every document

2024-06-27 13:34 UTC, chase commented on libreoffice-core/desktop/wasm/worker.ts
> +  loadFromExpandedParts: function(data: any) {
Let's avoid using any here, better to make a type for `{path: string, content: ArrayBuffer}` in `shared.d.ts` and use that everywhere, rather than hardcoding it in several places

2024-06-27 13:34 UTC, chase commented on libreoffice-core/framework/source/accelerators/presethandler.cxx
> +    return;
Why was this disabled? Seems kind of important, but I'm not sure.

2024-06-27 13:34 UTC, chase commented on libreoffice-core/framework/source/fwe/helper/titlehelper.cxx
> +    return; // MACRO
Does this disable the ability to get the document's internal title? Not sure if we need that for our UI yet, but might want to make a note of it somewhere

2024-06-27 13:34 UTC, chase commented on libreoffice-core/framework/source/layoutmanager/layoutmanager.cxx
> +    return;
Don't think we should shortcircuit the layout manager, this seems like a good way to have a lot of unpredictable behavior. Why was this necessary?

2024-06-27 13:34 UTC, chase commented on libreoffice-core/framework/source/loadenv/loadenv.cxx
> +    /* initializeUIDefaults(m_xContext, m_lMediaDescriptor, bUIMode, &m_pQuietInteraction); */
This disables the default interaction handler that's used to handle all kinds of things, is this necessary? Also seems conflicting to the previous code that sets `Silent` to true, because it no longer does anything.

2024-06-27 13:34 UTC, chase commented on libreoffice-core/framework/source/loadenv/loadenv.cxx
> +    return;
I'm guessing this was disabled due to the prior disabled code. Is the problem caused by `m_lMediaDescriptor.clear()`;

Again, don't want weird regressions if we can keep existing code alive.

2024-06-27 13:34 UTC, chase commented on libreoffice-core/framework/source/services/frame.cxx
Think this might cause problems when loading a new doc to replace, probably shouldn't disable this

2024-06-27 13:34 UTC, chase commented on libreoffice-core/include/LibreOfficeKit/LibreOfficeKit.h
Not required

2024-06-27 13:34 UTC, chase commented on libreoffice-core/include/LibreOfficeKit/LibreOfficeKit.hxx
Not required

2024-06-27 13:34 UTC, chase commented on libreoffice-core/include/comphelper/base64.hxx
Revert, don't want to deal with merge conflicts later over this :joy:

2024-06-27 13:34 UTC, chase commented on libreoffice-core/include/oox/core/filterdetect.hxx
Can drop the rxContext and use the `comphelper::getProcessComponentContext()` utility mentioned previously

2024-06-27 13:34 UTC, chase commented on libreoffice-core/oox/source/helper/expandedstorage.cxx
> +    return toHexString(hashVec);
Instead of internally storing the hash as a string, better so store the original vector. Faster to compare, takes less space, and we only need the hex string when we shuffle it back to our backend/the JS side of the API. And even then the JS API could return a typed memory view for this: `https://emscripten.org/docs/porting/connecting_cpp_and_javascript/embind.html#memory-views`

2024-06-27 13:34 UTC, chase commented on libreoffice-core/oox/source/helper/expandedstorage.cxx
> +    comphelper::Base64::decode(seqContent, helpers::toOUString(content));
Need to get rid of the base64 stuff and just assume content is an std::string made from an ArrayBuffer

2024-06-27 13:34 UTC, chase commented on libreoffice-core/oox/source/helper/expandedstorage.cxx
> +    std::string contentString(it->second.content.begin(), it->second.content.end());
This shouldn't be necessary since `it->second.content` is already a string and not a string reference, right?

2024-06-27 13:34 UTC, chase commented on libreoffice-core/oox/source/helper/expandedstorage.cxx
> +OUString toOUString(const std::string& value) { return OUString::createFromAscii(value.c_str()); }
This already exists as `OUString::fromUtf8`

2024-06-27 13:34 UTC, chase commented on libreoffice-core/oox/source/helper/expandedstorage.cxx
> +}
More efficient to use string view here, see my implementation for split in awrit here:
https://github.com/chase/awrit/blob/main/awrit/string/string_utils.cc#L11-L26

2024-06-27 13:34 UTC, chase commented on libreoffice-core/oox/source/helper/expandedstorage.cxx
> +        file.sha = helpers::getContentHash(file.content);
Isn't the sha already calculated on add?

2024-06-27 13:34 UTC, chase commented on libreoffice-core/oox/source/helper/expandedstorage.cxx
> +    SAL_WARN("expandedstorage", "cloneStreamElement: not implemented");
Should be able to implement this by simply making a new vector that's a copy of the contents and making that into a stream, I think?

2024-06-27 13:34 UTC, chase commented on libreoffice-core/oox/source/helper/expandedstorage.cxx
> +    return std::find(m_dirs.begin(), m_dirs.end(), helpers::toString(path)) != m_dirs.end();
Would probably be faster to store m_dirs as OUString rather than converting the path every call, convert once, basically

Same with most other cases in this file where we convert the string every single call

2024-06-27 13:34 UTC, chase commented on libreoffice-core/oox/source/helper/expandedstorage.cxx
> +        // TODO/LATER: in future the unification of the ID could be checked
Is this a todo from upstream?

2024-06-27 13:34 UTC, chase commented on libreoffice-core/oox/source/helper/storagebase.cxx
> +    SAL_WARN("storagebase", "open sub storage " << rElementName << " create missing " << bCreateMissing);
Should clean up the debugging warns now that we have proper debugging setup

2024-06-27 13:34 UTC, chase commented on libreoffice-core/package/source/xstor/owriteablestream.cxx
Revert removals here, want to avoid conflicts later

2024-06-27 13:34 UTC, chase commented on libreoffice-core/sfx2/source/doc/DocumentMetadataAccess.cxx
> +        SAL_WARN("metadata", "FAILED TO ADD CONTENT OR STYLE 1");
Debug warn

2024-06-27 13:34 UTC, chase commented on libreoffice-core/sfx2/source/doc/objstor.cxx
Isn't this necessary to load document metadata when we do an initial import?

2024-06-27 13:34 UTC, chase commented on libreoffice-core/sfx2/source/doc/objstor.cxx
> +            if (!comphelper::OStorageHelper::IsExpandedStorage()){
This is potentially why images aren't loading, I think images might count as an embedded object?

Why was this disabled?

2024-06-27 13:34 UTC, chase commented on libreoffice-core/sfx2/source/view/frmload.cxx
> +    SAL_WARN("frmload", "connecting frame controller and model together " << i_rFrame.is() << " "  << xController.is() << " " << i_rModel.is());
Debug warn

2024-06-27 13:34 UTC, chase commented on libreoffice-core/sfx2/source/doc/sfxbasemodel.cxx
> +    return; // MACRO
```suggestion
    return; // MACRO: CMIS properties are only added when loading from a remote file, which we never do
```

2024-06-27 13:34 UTC, chase commented on libreoffice-core/sfx2/source/view/frmload.cxx
> +    SAL_WARN("frmload", "bLoadSuccess " << bLoadSuccess);
debug warn

2024-06-27 13:34 UTC, chase commented on libreoffice-core/sfx2/source/view/lokhelper.cxx
> +    }
Revert to avoid conflicts later

2024-06-27 13:34 UTC, chase commented on libreoffice-core/desktop/source/app/main_wasm.cxx
> +        result.set("content", part->second);
It would be ideal to store the content as the vector of u8 and then return the typed memory view here, then have worker.ts send it over

2024-06-27 13:34 UTC, chase commented on libreoffice-core/desktop/source/lib/wasm_extensions.cxx
> +    aMediaDescriptor["Silent"] <<= false;
Comment contradictory to the code and we probably want this enabled I think?

2024-06-27 13:34 UTC, chase commented on libreoffice-core/sfx2/source/view/sfxbasecontroller.cxx
>  void SfxBaseController::ShowInfoBars( )
That's correct, this is only for opening from remote storage like Google Drive which we don't support this way anyway

2024-06-27 13:34 UTC, chase commented on libreoffice-core/sfx2/source/view/sfxbasecontroller.cxx
> +        /* ShowInfoBars( ); */
Provide reason it's not needed

2024-06-27 13:34 UTC, chase commented on libreoffice-core/sw/source/core/unocore/unotext.cxx
> +        /* m_pDoc->GetIDocumentUndoRedo().Undo(); */
Please revert then

2024-06-27 13:34 UTC, chase commented on libreoffice-core/sfx2/source/view/viewfrm.cxx
>      return pApp ? pApp->Get_Impl()->pViewFrame : nullptr;
Debug warn

2024-06-27 13:34 UTC, chase commented on libreoffice-core/sw/source/filter/ww8/docxexport.cxx
Revert

2024-06-27 13:34 UTC, chase commented on libreoffice-core/writerfilter/source/filter/WriterFilter.cxx
> -            SAL_WARN("writerfilter",
This seems valuable to have, why was it a removed?

2024-06-27 13:34 UTC, chase commented on libreoffice-core/writerfilter/source/filter/WriterFilter.cxx
> +        /* writerfilter::ooxml::OOXMLStream::Pointer_t pVBAProjectStream( */
I like the added security, shouldn't support VBA anyway lol

2024-06-27 15:15 UTC, synoet commented on libreoffice-core/desktop/source/lib/wasm_extensions.cxx
> +    uno::Reference<io::XInputStream> xEmptyInputStream(new comphelper::SequenceInputStream(aEmptyData));
I switched it. but this stream is not actually used anywhere. I believe certain checks just expect an input stream in the prop set for loading. But we use the actual expanded storage to read.

2024-06-27 15:42 UTC, synoet commented on libreoffice-core/oox/source/helper/expandedstorage.cxx
> +        // TODO/LATER: in future the unification of the ID could be checked
yup

2024-06-27 15:43 UTC, synoet commented on libreoffice-core/oox/source/helper/expandedstorage.cxx
> +        file.sha = helpers::getContentHash(file.content);
We need to recalculate the sha's after a save though I'll find a better way to implement this.

2024-06-27 15:52 UTC, synoet commented on libreoffice-core/sfx2/source/doc/objstor.cxx
> +            if (!comphelper::OStorageHelper::IsExpandedStorage()){
Removed : but unfortunately did not resolve issue with images

2024-06-27 15:55 UTC, synoet commented on libreoffice-core/framework/source/accelerators/presethandler.cxx
> +    return;
It does alot of unrelated storage operations that I don't think are needed and conflict with the expanded storage work. Though I'll specifically flag this off to only return if expanded storage is being used.

2024-06-27 15:57 UTC, synoet commented on libreoffice-core/framework/source/layoutmanager/layoutmanager.cxx
> +    return;
fixed

2024-06-27 15:59 UTC, synoet commented on libreoffice-core/framework/source/loadenv/loadenv.cxx
> +    /* initializeUIDefaults(m_xContext, m_lMediaDescriptor, bUIMode, &m_pQuietInteraction); */
fixed

2024-06-27 16:02 UTC, synoet commented on libreoffice-core/sfx2/source/doc/objstor.cxx
fixed

2024-06-27 16:12 UTC, synoet commented on libreoffice-core/oox/source/helper/expandedstorage.cxx
> +    std::string contentString(it->second.content.begin(), it->second.content.end());
no content is  a vec<int8>

2024-06-27 16:14 UTC, synoet commented on libreoffice-core/oox/source/helper/expandedstorage.cxx
> +    SAL_WARN("expandedstorage", "cloneStreamElement: not implemented");
I believe this isn't actually used anywhere, but I guess doesn't hurt to implement it just in case

2024-06-27 19:28 UTC, synoet commented on libreoffice-core/oox/source/helper/expandedstorage.cxx
> +        file.sha = helpers::getContentHash(file.content);
@chase Ive changed this logic to be a bit more clean.

After a save a `ImplCommit` is called on the store which will then re-calaculate the hash for the file's that have been changed, I think this is also eventually where the notification will be emitted from.

https://github.com/coparse-inc/lok-wasm/blob/ae07741d70d9be420058154b634b316b4afe852b/libreoffice-core/oox/source/helper/expandedstorage.cxx#L566

2024-06-28 06:25 UTC, chase requested changes
Looking solid, minor stuff at this point.

As I said in a few comments, I think making edge cases across the entirety of the sw/ for expanded storage doesn't scale well and will lead to merged conflicts from upstream fairly frequently. So if we can avoid that by abstracting at the storage layer or stream layer somehow so that things like relations and whatnot all do the right thing without having to change their usage, that'd be ideal.

2024-06-28 06:25 UTC, chase commented on libreoffice-core/desktop/source/app/main_wasm.cxx
> +    register_vector<int8_t>("IntVec");
We don't need this and `register_vector` adds _a lot_ of code for no good :joy:

2024-06-28 06:25 UTC, chase commented on libreoffice-core/desktop/wasm/soffice.d.ts
> +  getExpandedPart(path: string): {path: string, content: ArrayBuffer} | null;
Let's make `export type ExpandedPart = {path: string, content: ArrayBuffer}` here in `soffice.d.ts` rather than hard coding it in here, `shared.d.ts`, `index.ts`, and `worker.ts`

2024-06-28 06:25 UTC, chase commented on libreoffice-core/framework/source/accelerators/presethandler.cxx
> +#include "comphelper/storagehelper.hxx"
<>

2024-06-28 06:25 UTC, chase commented on libreoffice-core/desktop/inc/lib/wasm_extensions.hxx
> +#include "sal/types.h"
<>

2024-06-28 06:25 UTC, chase commented on libreoffice-core/include/comphelper/storagehelper.hxx
> +inline constexpr OUString WORD_DIR_NAME = OUString(u"word"_ustr);
```suggestion
inline constexpr OUString WORD_DIR_NAME = u"word"_ustr;
```

2024-06-28 06:25 UTC, chase commented on libreoffice-core/include/comphelper/vecstream.hxx
>  #include <com/sun/star/embed/XExtendedStorageStream.hpp>
Looks like you have this header 3 times

2024-06-28 06:25 UTC, chase commented on libreoffice-core/include/oox/helper/expandedstorage.hxx
> +#include "sal/types.h"
<>

2024-06-28 06:25 UTC, chase commented on libreoffice-core/oox/source/drawingml/misccontexts.cxx
> +            aFragmentPath = getFragmentPathFromRelId( rAttribs.getStringDefaulted( R_TOKEN( embed )) );
It almost seems like we should just implement the `IsExpandedStorage` stuff at getFragmentPathFromRelId instead here?

2024-06-28 06:25 UTC, chase commented on libreoffice-core/oox/source/helper/expandedstorage.cxx
> +#include <comphelper/base64.hxx>
Don't need this anymore, I think

2024-06-28 06:25 UTC, chase commented on libreoffice-core/oox/source/helper/expandedstorage.cxx
Re: https://github.com/coparse-inc/lok-wasm/pull/43#discussion_r1657049453

Seems like we're still storing things as `std::string` and converting every call, is there a reason?

2024-06-28 06:25 UTC, chase commented on libreoffice-core/oox/source/helper/expandedstorage.cxx
> +// https://github.com/chase/awrit/blob/main/awrit/string/string_utils.cc#L11-L26
This won't be the main branch for long, haha

```suggestion
// https://github.com/chase/awrit/blob/546772897461f7a4654d30450547f95f11c0f6b6/awrit/string/string_utils.cc#L11-L26
```

2024-06-28 06:25 UTC, chase commented on libreoffice-core/oox/source/helper/graphichelper.cxx
> +                inputStream = mxStorage->openInputStream(rStreamName);
Similar to my previous comment, maybe we should add the IsExpandedStorage stuff to openInputStream, that way we don't need to chase down every single usage of it throughout the codebase? Would also make the code a lot cleaner I think and reduce merge conflicts later.

2024-06-28 06:25 UTC, chase commented on libreoffice-core/sfx2/source/view/sfxbasecontroller.cxx
> +        // which we don't support right now
We will never support this in LOK, since this would require doing networking stuff from LOK when it's much simpler to do in JS or in the backend

2024-06-28 06:25 UTC, chase commented on qa-env/src/App.tsx
> +import { downloadFile, unzipDocxFile } from './utils';
For future testing, but not necessary for now, we'd ideally have a cycle of:

1. Open .docx
2. Take a snapshot of the pages
3. Save to expanded parts
4. Open expanded parts
5. Check that snapshots are the same
6. Save to new .docx
7. Open new .docx
8. Check that snapshots are the same

2024-06-28 06:25 UTC, chase commented on qa-env/src/utils.ts
> +    console.log("processing file", key);
debug comment

2024-07-01 15:08 UTC, synoet commented on libreoffice-core/include/comphelper/vecstream.hxx
>  #include <com/sun/star/embed/XExtendedStorageStream.hpp>
lol

2024-07-02 19:42 UTC, synoet commented on libreoffice-core/oox/source/helper/graphichelper.cxx
> +                inputStream = mxStorage->openInputStream(rStreamName);
Was able to get this to work after all.

2024-07-02 20:06 UTC, synoet commented on libreoffice-core/oox/source/helper/expandedstorage.cxx
I went through and tried to clean it up. Personally I stuck with std::string for some internal types since I found it easier to work with and do path manipulation and splitting. 

There is a fat tail of optimizations and improvements that can be made, I'll add them to their own ticket and revisit them once we get some time.

2024-07-03 00:40 UTC, chase commented on libreoffice-core/oox/source/helper/expandedstorage.cxx
> +    /* std::lock_guard<std::mutex> lock(m_aMutex); */
Was disabling this intentional? Not sure if we realistically need to worry about a data race here, just checking since it was commented out instead of removed outright.

2024-07-03 00:49 UTC, chase requested changes

2024-07-03 00:49 UTC, chase commented on libreoffice-core/writerfilter/source/dmapper/StyleSheetTable.cxx
>  {
Definitely shouldn't return early for the defaults table, is expanded storage broken without this or was this accidentally left in?

2024-07-03 14:01 UTC, synoet commented on libreoffice-core/writerfilter/source/dmapper/StyleSheetTable.cxx
>  {
Good catch this was accidentally left in.

2024-07-03 14:01 UTC, synoet commented on libreoffice-core/oox/source/helper/expandedstorage.cxx
> +    /* std::lock_guard<std::mutex> lock(m_aMutex); */
Ah, sorry yeah I need to remove it. Since I need to make nested `openStreamElement` calls to read the relationships into a stream I was locking myself out from the inner call. Will just remove entirely

2024-07-03 14:57 UTC, chase approved these changes

2024-07-03 17:15 UTC, merged