ADD Save returns filesChanged
chase/lok-wasm pull request #80
Opened 2024-07-08 20:23 UTC by synoet

`doc.save()` not returns a list of `{path: string, sha: string}` of files that have been changed during save.

2024-07-08 20:25 UTC, whutchinson98 commented on libreoffice-core/include/oox/helper/expandedstorage.hxx
> +        SAL_WARN("expanded storage", "MaybeNotifier");
Is this warning needed?

2024-07-09 23:37 UTC, chase requested changes
Overall good. Just minor cleanup. Bump the version file to v0.1.0 since this has a breaking API change.

2024-07-09 23:37 UTC, chase commented on libreoffice-core/include/oox/helper/expandedstorage.hxx
> +#include "sal/log.hxx"
Leftover from debugging

2024-07-09 23:37 UTC, chase commented on qa-env/src/App.tsx
> +window.expandedSave = async function save(doc: DocumentClient | null) {
The reason why I made the PDF save as a window function is because it couldn't be called without the downloadFile utility, but I'm the case of expanded save, this can just be called with `d.save()`

2024-07-09 23:37 UTC, chase commented on libreoffice-core/desktop/wasm/shared.d.ts
> +  saveAs(format: 'docx' | 'pdf', filename: string): ArrayBuffer;
Just making note here that the API change will have to be adjusted in monorepo if there's any usage at the moment.

2024-07-10 12:43 UTC, synoet commented on libreoffice-core/desktop/wasm/shared.d.ts
> +  saveAs(format: 'docx' | 'pdf', filename: string): ArrayBuffer;
yep

2024-07-10 12:56 UTC, chase approved these changes

2024-07-10 12:57 UTC, merged