Fix some expanded storage bugs
chase/lok-wasm pull request #82
Opened 2024-07-11 16:55 UTC by chase

Essentially, the original code had vectors allocated on stack. When the life-time of the stack expires (when the original call ends), the vector is freed because the references aren't retained.

Also, the original code assumes despite truncate not being set as a mode flag that it shouldn't reset the output vector, when really it should because the original code always started with a fresh zip storage, essentially always creating a new file.

Lastly, the open mode flags weren't treated as bit flags.

There might be regressions @synoet so please be thorough when testing!

2024-07-11 17:13 UTC, synoet requested changes

2024-07-11 17:13 UTC, synoet commented on libreoffice-core/comphelper/source/streaming/vecstream.cxx
> +    m_vec->clear();
This won't work as expected. I don't think we can make the assumption that we can clear the underlying vec of bytes when opening an output stream. I think that certain places could still have a ref to a inputStream pointing to that vec. 

Doing this makes some document corrupted, recoverable but corrupted.

2024-07-12 13:08 UTC, chase commented on libreoffice-core/comphelper/source/streaming/vecstream.cxx
> +    m_vec->clear();
From Slack, basically, this does work, but the XRelationAccess and other original file relation code isn't up to par for whatever reason. @synoet will be picking it up from there

2024-07-15 03:56 UTC, synoet approved these changes

2024-07-15 11:15 UTC, merged